/****TEXT ENTRY****/
export const EDIT_TEXT = 'EDIT_TEXT';
export const ANALYZE_TEXT = 'ANALYZE_TEXT';

/****CONTROL PANEL****/
export const SELECT_NGRAM = 'SELECT_NGRAM';
export const SELECT_NGRAM_POSITION = 'SELECT_NGRAM_POSITION';
export const FILTER_SENTIMENT = 'FILTER_SENTIMENT';
export const FILTER_JSON = 'FILTER_JSON';
export const SELECT_DEPTH = 'SELECT_DEPTH';
export const CALC_CURRENT_TOKEN_DATA = 'CALC_CURRENT_TOKEN_DATA';

/****VISUALIZTION****/
export const SET_PERSPECTIVE = 'SET_PERSPECTIVE';
