/****TEXT ENTRY****/
export const EDIT_TEXT = 'EDIT_TEXT';
export const ANALYZE_TEXT = 'ANALYZE_TEXT';
export const HANDLE_ENTRY_FOCUS = 'HANDLE_ENTRY_FOCUS';

/****CONTROL PANEL****/
export const SELECT_DOCUMENT = 'SELECT_DOCUMENT';
export const FILTER_SENTENCES = 'FILTER_SENTENCES';
export const SELECT_VISUAL_FOCUS = 'SELECT_VISUAL_FOCUS';
export const SELECT_NGRAM_POSITION = 'SELECT_NGRAM_POSITION';
export const FILTER_SENTIMENT = 'FILTER_SENTIMENT';
export const FILTER_JSON = 'FILTER_JSON';

/****VISUALIZTION****/
export const SET_PERSPECTIVE = 'SET_PERSPECTIVE';
